# Use postgres/example user/password credentials
version: '3.1'

volumes:
  database:
    driver: local

services:
  postgres:
    platform: linux/amd64
    image: postgres
    container_name: musigrow-postgresql
    restart: always
    expose:
      - 5432
    ports:
        - 5432:5432
    environment:
      POSTGRES_PASSWORD: musigrow
      POSTGRES_USER: musigrow
      POSTGRES_DB: musigrow
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - database:/var/lib/postgresql/data
