#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm test
npx lint-staged

BRANCH=$(git rev-parse --abbrev-ref HEAD)
REGEX="^(develop|master|release|((feature|bigfeature|task|bugfix|hotfix)\/[A-Z]+-[0-9]+_[a-z]+-.+))$"

if ! [[ $BRANCH =~ $REGEX ]]; then
    echo "Your commit was rejected due to branching name"
    echo "Please rename your branch with $REGEX syntax"
    exit 1
fi
