name: Lighthouse

on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    lighthouseci:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: apps/musigrow-app
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'yarn'
            - run: cd ../.. && rm -rf node_modules && yarn cache clean && yarn install && yarn build
            - run: npm install -g @lhci/cli@0.8.x
            - run: cd apps/musigrow-app
            - run: lhci autorun
